config/routes.rb
Rails.application.routes.draw do
  # カンバンボード表示用のルート (1ユーザー1ボードなので単数リソース)
  resource :board, only: [:show]

  # レーンとカードのCRUD操作用のルート
  resources :lanes, only: [:create, :update, :destroy] do
    resources :cards, only: [:new, :create] # :new を追加
  end

  resources :cards, only: [:update, :destroy] do
    member do
      patch :move
    end
  end

  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"

  get "users/search" => "users#search"
  post "users/:id/update" => "users#update"
  get "users/:id/edit" => "users#edit"
  post "users/create" => "users#create"
  get "signup" => "users#new"
  get "users/index" => "users#index"
  get "users/:id" => "users#show"
  get "login" => "users#login_form"
  post "login" => "users#login"
  post "logout" => "users#logout"
  get "users/:id/likes" => "users#likes"
  post "users/:id/discard" => "users#discard"

  get "posts/index" => "posts#index"
  get "posts/new" => "posts#new"
  # get "posts/new" => "posts#new_fixed"
  get "posts/:id" => "posts#show"
  post "posts/create" => "posts#create"
  get "posts/:id/edit" => "posts#edit"
  get "posts/:id/word_cloud" => "posts#word_cloud"
  # get "posts/:id/edit" => "posts#edit_fixed"
  post "posts/:id/update" => "posts#update"
  get "posts/:id/destroy" => "posts#destroy"

  get 'schedules/index', to: 'schedules#index', as: 'schedules_index'
  get "schedules/new" => "schedules#new"
  # get "schedules/new" => "schedules#new_fixed"
  get "schedules/:id" => "schedules#show"
  post "schedules/create" => "schedules#create"
  get "schedules/:id/edit" => "schedules#edit"
  get 'schedules/date/:date/edit', to: 'schedules#edit_by_date', as: :edit_schedule_by_date
  post 'schedules/date/:date/update', to: 'schedules#update_by_date'
  # post "schedules/:id/update" => "schedules#update"
  get "schedules/:id/destroy" => "schedules#destroy"

  resources :memos

  get "/" => "home#top"
  get "about" => "home#about"

  resources :tasks do
    collection do
      get 'gantt'
    end
  end

  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :lane
  # 優先度をenumで定義すると便利です
  enum priority: { low: 1, medium: 2, high: 3 }
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
      before_action :authenticate_user
      
      def new
        @lane = Lane.find(params[:lane_id])
        @card = @lane.cards.new
      end

      def create
        @lane = Lane.find(params[:lane_id])
        @card = @lane.cards.new(card_params)
        
        if @card.save
          # 成功時はTurbo Streamを返す
          respond_to do |format|
            format.turbo_stream
          end
        else
          # 失敗時はフォームを再表示
          render :new, status: :unprocessable_entity
        end
      end

      def move
        card = Card.find(params[:id])
        # 所属レーンと表示順を更新
        card.update(lane_id: params[:lane_id], position: params[:position])
        head :ok # 成功ステータスのみを返す
      end

      def destroy
        @card = Card.find(params[:id])
        @card.destroy
        respond_to do |format|
          format.turbo_stream
        end
      end

      private

      def card_params
        params.require(:card).permit(:title, :priority, :due_date)
      end
    end

app/views/cards/_form.html.erb
<%= form_with(model: [@lane, @card], class: "mt-2") do |form| %>
  <%# バリデーションエラーメッセージの表示 %>
  <% if form.object.errors.any? %>
    <div class="alert alert-danger p-2 small">
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div class="card">
    <div class="card-body p-2">
      <div class="mb-2">
        <%= form.text_field :title, class: "form-control form-control-sm", placeholder: "カードのタイトル", required: true %>
      </div>
      <div class="mb-2">
        <%= form.label :priority, "優先度", class: "form-label small" %>
        <%# `Card.priorities`はenumで定義したものを想定 %>
        <%= form.select :priority, Card.priorities.keys.map { |k| [I18n.t("activerecord.attributes.card.priorities.#{k}"), k] }, {}, {class: "form-select form-select-sm"} %>
      </div>
      <div class="mb-2">
        <%= form.label :due_date, "期日", class: "form-label small" %>
        <%= form.date_field :due_date, class: "form-control form-control-sm" %>
      </div>
      <div class="d-flex justify-content-end mt-2">
        <%= form.submit "作成", class: "btn btn-primary btn-sm" %>
        <%# キャンセル時はボードのページを再読み込みしてフォームを閉じる %>
        <%= link_to "キャンセル", board_path, class: "btn btn-light btn-sm ms-1" %>
      </div>
    </div>
  </div>
<% end %>

app/views/cards/create.turbo_stream.erb
<%# 新しいカードをレーンの末尾に追加 %>
<%= turbo_stream.append "lane_#{@lane.id}_cards", partial: "boards/card", locals: { card: @card } %>

<%# 入力フォームを「+ カードを追加」リンクに戻す %>
<%= turbo_stream.update "new_card_for_lane_#{@lane.id}" do %>
  <%= link_to "+ カードを追加", new_lane_card_path(@lane), class: "btn btn-secondary btn-sm mt-2" %>
<% end %>

app/views/cards/destroy.turbo_stream.erb
<%= turbo_stream.remove @card %>

app/views/cards/new.html.erb
<%= turbo_frame_tag "new_card_for_lane_#{@lane.id}" do %>
  <%= render "form", lane: @lane, card: @card %>
<% end %>